apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: guestbook-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-backend
  template:
    metadata:
      labels:
        app: guestbook-backend
    spec:
      containers:
      - name: guestbook-backend
        image: guestbook-backend:v1
        imagePullPolicy: IfNotPresent # Crucial: Tells K8s to use the local image we just built
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_MONGODB_URI
          value: "mongodb://guestbook-db:27017/guestbook"
